name: netxlif
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^3.0.0-dev.16
  gap: ^3.0.1
  http: ^1.4.0
  riverpod_annotation: ^3.0.0-dev.16
  shimmer_animation: ^2.2.2
  youtube_player_flutter: ^9.1.2

dev_dependencies:
  build_runner: null
  custom_lint: null
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon-app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
